# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fozziejoin_wrappers", use_symbols = TRUE, package_name = "fozziejoin")

#' @usage NULL
#' @useDynLib fozziejoin, .registration = TRUE
NULL

fozzie_string_join_rs <- function(df1, df2, by, method, how, max_distance, distance_col, q, max_prefix, prefix_weight, nthread) .Call(wrap__fozzie_string_join_rs, df1, df2, by, method, how, max_distance, distance_col, q, max_prefix, prefix_weight, nthread)

fozzie_difference_join_rs <- function(df1, df2, by, how, max_distance, distance_col, nthread) .Call(wrap__fozzie_difference_join_rs, df1, df2, by, how, max_distance, distance_col, nthread)

fozzie_distance_join_rs <- function(df1, df2, by, method, how, max_distance, distance_col, nthread) .Call(wrap__fozzie_distance_join_rs, df1, df2, by, method, how, max_distance, distance_col, nthread)

fozzie_interval_join_rs <- function(df1, df2, by, how, overlap_type, maxgap, minoverlap, interval_mode, nthread) .Call(wrap__fozzie_interval_join_rs, df1, df2, by, how, overlap_type, maxgap, minoverlap, interval_mode, nthread)

fozzie_regex_join_rs <- function(df1, df2, by, how, ignore_case, nthread) .Call(wrap__fozzie_regex_join_rs, df1, df2, by, how, ignore_case, nthread)

#' @title Get Number of Threads in the Global Thread Pool
#' @description This function retrieves the current number of threads
#' allocated by the Rayon thread pool. Understanding this value can
#' be useful for optimizing the parallelization capacity of your computations.
#' @return A single numeric value indicating the number of threads in the global thread pool.
#' @export
get_nthread_default <- function() .Call(wrap__get_nthread_default)


# nolint end
